# Generated by Django 4.0 on 2021-12-29 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default=datetime.datetime(2021, 12, 29, 11, 38, 27, 941800, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
