# Generated by Django 4.0 on 2021-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_destination_description_alter_destination_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
